export const eventsData = [
    {
        id: 1,
        category: 'Annual Event',
        title: 'Science & Technology Exhibition',
        description: 'Students showcase innovative projects in science, tech, and engineering fields.',
        date: 'April 5, 2026',
        image: 'https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?w=800&q=80',
    },
    {
        id: 2,
        category: 'Cultural',
        title: 'Islamic Cultural Fest',
        description: 'A celebration of Islamic heritage through art, poetry, and cultural performances.',
        date: 'April 12, 2026',
        image: 'https://images.unsplash.com/photo-1519817650390-64a93db51149?w=800&q=80',
    },
    {
        id: 3,
        category: 'Sports',
        title: 'Annual Sports Day',
        description: 'Inter-department sports competition featuring athletics, football, and cricket.',
        date: 'April 20, 2026',
        image: 'https://images.unsplash.com/photo-1526232761682-d26e03ac148e?w=800&q=80',
    },
    {
        id: 4,
        category: 'Seminar',
        title: 'Career Guidance Seminar',
        description: 'Industry experts guide students on career paths, higher education, and skill building.',
        date: 'May 2, 2026',
        image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80',
    },
    {
        id: 5,
        category: 'Workshop',
        title: 'Arabic Calligraphy Workshop',
        description: 'Learn the art of Arabic calligraphy from experienced masters of the craft.',
        date: 'May 10, 2026',
        image: 'https://images.unsplash.com/photo-1585779034823-7e9ac8faec70?w=800&q=80',
    },
    {
        id: 6,
        category: 'Activity',
        title: 'Nature Trail & Eco Camp',
        description: 'An outdoor learning experience focused on environment and sustainability.',
        date: 'May 18, 2026',
        image: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=800&q=80',
    },
]